export const PRODUCT_CREATE = "PRODUCT_CREATE";
export const PRODUCT_UPDATE = "PRODUCT_UPDATE";
export const PRODUCT_DELETE = "PRODUCT_DELETE";
export const PRODUCT_CHECKOUT = "PRODUCT_CHECKOUT";
export const REMOVE_PRODUCT_CHECKOUT = "REMOVE_PRODUCT_CHECKOUT";
export const VIEW_POST = "VIEW_POST";
